version: '3.8'

services:
  book_app_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - book_app_network

networks:
  book_app_network:
    external: true